"""add_messages2

Revision ID: bef760ff3969
Revises: ba8dbae01451
Create Date: 2023-07-02 23:50:00.883309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef760ff3969'
down_revision = 'ba8dbae01451'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
