"""update5

Revision ID: 0afef6837777
Revises: 9cfbd56baf92
Create Date: 2023-06-26 17:51:59.471367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0afef6837777'
down_revision = '9cfbd56baf92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
