"""add_messages7

Revision ID: 6e225f0fc99c
Revises: 59c206fdbc5f
Create Date: 2023-07-03 18:47:40.817579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e225f0fc99c'
down_revision = '59c206fdbc5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
