"""add_messages6

Revision ID: 59c206fdbc5f
Revises: dbfbc50e64a0
Create Date: 2023-07-03 16:20:21.365224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59c206fdbc5f'
down_revision = 'dbfbc50e64a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
